version: "3.8"
services:

  main-app:
    build:
      context: './main_app'
    restart: always
    ports: 
      - 80:80
    volumes:
        # - ./main_app/httpd.conf:/usr/local/apache2/conf/httpd.conf
        - ./main_app/app/:/var/www/html/
    networks:
      proj2-net:
  
#  mysql:
#    build:
#      context: './mysql'
#    restart: always
#    volumes:
#       - mysql-storage:/var/lib/mysql
#    ports:
#      - 3306:3306
#    networks:
#      proj2-net:
#    environment:
#      MYSQL_ROOT_PASSWORD: 1234securePass

  # MySQL db management
  adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080
      networks:
        proj2-net:

  db-service:
      build:
        context: './database_service'
      volumes:
        - ./database_service/httpd.conf:/usr/local/apache2/conf/httpd.conf
        - ./database_service/app/:/var/www/html/
      networks:
        proj2-net:
      ports:
        - 9003:80

  mongo:
     build:
       context: './mongo'
     ports:
       - 27017:27017
     volumes:
       - mongo-storage:/data/db
     networks:
       proj2-net:
     environment:
       MONGO_INITDB_ROOT_USERNAME: root
       MONGO_INITDB_ROOT_PASSWORD: 1234securePass

  mongo-express:
     image: mongo-express
     depends_on:
       - mongo
     ports:
       - 8081:8081
     networks:
        proj2-net:
     environment:
       ME_CONFIG_MONGODB_ADMINUSERNAME: root
       ME_CONFIG_MONGODB_ADMINPASSWORD: 1234securePass

  keyrock:
    image: fiware/idm:7.6.0
    container_name: fiware-keyrock
    depends_on:
      - mysql-keyrock
    ports:
      - 3000:3000
      - 443:443
    networks:
        proj2-net:
    environment:
      - DEBUG=idm:*
      - IDM_DB_HOST=mysql-keyrock
      - IDM_HOST=http://localhost:3000
      - IDM_PORT=3000
      - IDM_DB_PASS=secret
      - IDM_DB_USER=root
      - IDM_ADMIN_USER=admin
      - IDM_ADMIN_EMAIL=admin@test.com
      - IDM_ADMIN_PASS=1234

  mysql-keyrock:
    restart: always
    image: mysql:5.7
    container_name: db-mysql-keyrock
    ports:
      - 3306:3306
    networks:
        proj2-net:
    environment:
      - 'MYSQL_ROOT_PASSWORD=secret'
    volumes:
      - mysql-keyrock:/var/lib/mysql


  db-proxy:
    image: fiware/pep-proxy
    depends_on:
      - keyrock
      - db-service
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - 9004:9004
    networks:
      proj2-net:
    environment:
      - 'PEP_PROXY_APP_HOST=db-service'
      - 'PEP_PROXY_APP_PORT=80'
      - 'PEP_PROXY_PORT=9004'
      - 'PEP_PROXY_IDM_HOST=keyrock'
      - 'PEP_PROXY_HTTPS_ENABLED=false'
      - 'PEP_PROXY_AUTH_ENABLED=false'
      - 'PEP_PROXY_IDM_SSL_ENABLED=false'
      - 'PEP_PROXY_IDM_PORT=3000'
      - 'PEP_PROXY_APP_ID=09e67316-d0fa-490a-a2c9-58107a67cab8'
      - 'PEP_PROXY_USERNAME=pep_proxy_e30a4575-25e1-43d4-8abf-b12452759d72'
      - 'PEP_PASSWORD=pep_proxy_796fbac3-8bcf-4f67-b4dd-1e0aa88a883a'
      - 'PEP_PROXY_PDP=idm'
      - 'PEP_PROXY_MAGIC_KEY=123456'

  orion:    # Orion Context Broker
    image: "fiware/orion"
    links:
      - mongo-orion
    ports:
      - "1026:1026"
    networks:
      proj2-net:
    command: -dbhost mongo-orion

  mongo-orion:
    image: mongo
    networks:
      proj2-net:
    volumes:
      - mongo-orion:/data/db

  orion-proxy:
    image: fiware/pep-proxy
    depends_on:
      - keyrock
      - orion
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - 1027:1027
    networks:
      proj2-net:
    environment:
      - 'PEP_PROXY_APP_HOST=orion'
      - 'PEP_PROXY_APP_PORT=1026'
      - 'PEP_PROXY_PORT=1027'
      - 'PEP_PROXY_IDM_HOST=keyrock'
      - 'PEP_PROXY_HTTPS_ENABLED=false'
      - 'PEP_PROXY_AUTH_ENABLED=false'
      - 'PEP_PROXY_IDM_SSL_ENABLED=false'
      - 'PEP_PROXY_IDM_PORT=3000'
      - 'PEP_PROXY_APP_ID=09e67316-d0fa-490a-a2c9-58107a67cab8'
      - 'PEP_PROXY_USERNAME=pep_proxy_e30a4575-25e1-43d4-8abf-b12452759d72'
      - 'PEP_PASSWORD=pep_proxy_796fbac3-8bcf-4f67-b4dd-1e0aa88a883a'
      - 'PEP_PROXY_PDP=idm'
      - 'PEP_PROXY_MAGIC_KEY=123456'

volumes:
  mysql-storage:
  mongo-storage:
  mysql-keyrock:
  mongo-orion:

networks:
  proj2-net:
    external: true