version: "3.8"
services:

  main-app:
    build:
      context: './main_app'
    restart: always
    ports: 
      - 80:80
    volumes:
        # - ./main_app/httpd.conf:/usr/local/apache2/conf/httpd.conf
        - ./main_app/app/:/var/www/html/
    networks:
      proj2-net:
  
  mysql:
    build:
      context: './mysql'
    restart: always
    volumes:
       - mysql-storage:/var/lib/mysql
    ports: 
      - 3306:3306
    networks:
      proj2-net:
    environment:
      MYSQL_ROOT_PASSWORD: 1234securePass

  # MySQL db management
  adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080
      networks:
        proj2-net:


  db-service:
      build:
        context: './database_service'
      volumes:
        - ./database_service/httpd.conf:/usr/local/apache2/conf/httpd.conf
        - ./database_service/app/:/var/www/html/
      networks:
        proj2-net:
      ports:
        - 9003:80

  mongo:
     build:
       context: './mongo'
     ports:
       - 27017:27017
     volumes:
       - mongo-storage:/data/db
     networks:
       proj2-net:
     environment:
       MONGO_INITDB_ROOT_USERNAME: root
       MONGO_INITDB_ROOT_PASSWORD: 1234securePass

  mongo-express:
     image: mongo-express
     depends_on:
       - mongo
     ports:
       - 8081:8081
     networks:
        proj2-net:
     environment:
       ME_CONFIG_MONGODB_ADMINUSERNAME: root
       ME_CONFIG_MONGODB_ADMINPASSWORD: 1234securePass

  # keyrock: // Keyrock IDM
  #   image: "fiware/idm"
  
  # ocb:    // Orion Context Broken
  #   image: "fiware/orion"
  #   links:
  #    - mongo
  #    ports:
  #    - "1026:1026"
  
  # proxy:  // PEP Proxy Wilma
  #   image: "fiware/pep-proxy"
  
volumes:
  mysql-storage:
  mongo-storage:

networks:
  proj2-net:
    external: true